app:
  local-url: http://localhost:${server.port}
server:
  port: 8080
spring:
  application:
    name: ticketNG-project-rest
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketng
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    data: classpath:data.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            enabled: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    username: dennis.salmaz@gmail.com
    password: Dsalmaz-11
security:
  jwt:
    secret-key: ticketng
springdoc:
  swagger-ui:
    path: /swagger-ui.html








